-- +goose Up
INSERT INTO roles (name)
VALUES
    ('guest'),
    ('client'),
    ('assistant'),
    ('admin')
ON CONFLICT (name) DO NOTHING;

INSERT INTO permissions (name)
VALUES
    ('auth.register'),
    ('auth.login'),
    ('profile.view.own'),
    ('profile.edit.own'),
    ('profile.view.any'),
    ('profile.block'),
    ('profile.unblock'),
    ('change.user.subscription'),
    ('sport_plan.view'),
    ('sport_plan.generate.ai'),
    ('sport_plan.edit'),
    ('progress.view'),
    ('schedule.view'),
    ('activity.create'),
    ('match.create'),
    ('match.invite.users'),
    ('match.confirm.participation'),
    ('match.enter.result'),
    ('match.manage.any'),
    ('rating.view'),
    ('friends.view'),
    ('friends.add'),
    ('booking.request'),
    ('booking.manage'),
    ('booking.cancel'),
    ('shop.view'),
    ('order.create'),
    ('order.process'),
    ('order.view.own'),
    ('order.view.any'),
    ('wallet.view'),
    ('wallet.topup'),
    ('wallet.reserve'),
    ('wallet.writeoff'),
    ('wallet.force.adjust'),
    ('subscription.view'),
    ('subscription.purchase'),
    ('subscription.cancel'),
    ('chat.view'),
    ('chat.send'),
    ('chat.files.send'),
    ('survey.fill'),
    ('survey.view.own'),
    ('survey.view.any'),
    ('specialists.view'),
    ('specialists.manage'),
    ('sport_objects.view'),
    ('sport_objects.manage'),
    ('services.manage'),
    ('news.view'),
    ('news.manage'),
    ('analytics.view'),
    ('finance.view'),
    ('finance.export'),
    ('assistants.manage'),
    ('system.notifications.receive'),
    ('admin.logs.view')
ON CONFLICT (name) DO NOTHING;

WITH role_perm (role_name, permission_name) AS (
    VALUES
        ('guest', 'auth.register'),
        ('guest', 'auth.login'),
        ('guest', 'profile.view.own'),
        ('guest', 'profile.edit.own'),
        ('guest', 'sport_plan.view'),
        ('guest', 'schedule.view'),
        ('guest', 'match.confirm.participation'),
        ('guest', 'rating.view'),
        ('guest', 'friends.view'),
        ('guest', 'friends.add'),
        ('guest', 'shop.view'),
        ('guest', 'subscription.view'),
        ('guest', 'subscription.purchase'),
        ('guest', 'chat.view'),
        ('guest', 'news.view'),

        ('client', 'auth.register'),
        ('client', 'auth.login'),
        ('client', 'profile.view.own'),
        ('client', 'profile.edit.own'),
        ('client', 'sport_plan.view'),
        ('client', 'sport_plan.generate.ai'),
        ('client', 'progress.view'),
        ('client', 'schedule.view'),
        ('client', 'activity.create'),
        ('client', 'match.create'),
        ('client', 'match.invite.users'),
        ('client', 'match.confirm.participation'),
        ('client', 'match.enter.result'),
        ('client', 'rating.view'),
        ('client', 'friends.view'),
        ('client', 'friends.add'),
        ('client', 'booking.request'),
        ('client', 'booking.cancel'),
        ('client', 'shop.view'),
        ('client', 'order.create'),
        ('client', 'order.view.own'),
        ('client', 'wallet.view'),
        ('client', 'wallet.topup'),
        ('client', 'wallet.reserve'),
        ('client', 'subscription.view'),
        ('client', 'subscription.purchase'),
        ('client', 'subscription.cancel'),
        ('client', 'chat.view'),
        ('client', 'chat.send'),
        ('client', 'chat.files.send'),
        ('client', 'survey.fill'),
        ('client', 'survey.view.own'),
        ('client', 'news.view'),

        ('assistant', 'auth.register'),
        ('assistant', 'auth.login'),
        ('assistant', 'profile.view.own'),
        ('assistant', 'profile.view.any'),
        ('assistant', 'match.manage.any'),
        ('assistant', 'booking.manage'),
        ('assistant', 'booking.cancel'),
        ('assistant', 'order.process'),
        ('assistant', 'order.view.any'),
        ('assistant', 'chat.view'),
        ('assistant', 'chat.send'),
        ('assistant', 'chat.files.send'),
        ('assistant', 'survey.view.any'),
        ('assistant', 'specialists.view'),
        ('assistant', 'specialists.manage'),
        ('assistant', 'sport_objects.view'),
        ('assistant', 'sport_objects.manage'),
        ('assistant', 'news.manage'),

        ('admin', 'auth.register'),
        ('admin', 'auth.login'),
        ('admin', 'profile.view.own'),
        ('admin', 'profile.view.any'),
        ('admin', 'profile.block'),
        ('admin', 'profile.unblock'),
        ('admin', 'change.user.subscription'),
        ('admin', 'sport_plan.view'),
        ('admin', 'progress.view'),
        ('admin', 'schedule.view'),
        ('admin', 'match.manage.any'),
        ('admin', 'rating.view'),
        ('admin', 'booking.manage'),
        ('admin', 'booking.cancel'),
        ('admin', 'shop.view'),
        ('admin', 'order.view.any'),
        ('admin', 'wallet.view'),
        ('admin', 'wallet.force.adjust'),
        ('admin', 'subscription.view'),
        ('admin', 'chat.view'),
        ('admin', 'chat.send'),
        ('admin', 'chat.files.send'),
        ('admin', 'survey.view.any'),
        ('admin', 'specialists.view'),
        ('admin', 'specialists.manage'),
        ('admin', 'sport_objects.view'),
        ('admin', 'sport_objects.manage'),
        ('admin', 'services.manage'),
        ('admin', 'news.view'),
        ('admin', 'news.manage'),
        ('admin', 'analytics.view'),
        ('admin', 'finance.view'),
        ('admin', 'finance.export'),
        ('admin', 'assistants.manage'),
        ('admin', 'system.notifications.receive'),
        ('admin', 'admin.logs.view')
)
INSERT INTO role_permissions (role_id, permission_id)
SELECT
    r.id,
    p.id
FROM role_perm rp
JOIN roles r ON r.name = rp.role_name
JOIN permissions p ON p.name = rp.permission_name
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- +goose Down
UPDATE users
SET role_id = NULL
WHERE role_id IN (
    SELECT id
    FROM roles
    WHERE name IN ('guest', 'client', 'assistant', 'admin')
);

DELETE FROM role_permissions
WHERE role_id IN (
    SELECT id
    FROM roles
    WHERE name IN ('guest', 'client', 'assistant', 'admin')
)
OR permission_id IN (
    SELECT id
    FROM permissions
    WHERE name IN (
        'auth.register',
        'auth.login',
        'profile.view.own',
        'profile.edit.own',
        'profile.view.any',
        'profile.block',
        'profile.unblock',
        'change.user.subscription',
        'sport_plan.view',
        'sport_plan.generate.ai',
        'sport_plan.edit',
        'progress.view',
        'schedule.view',
        'activity.create',
        'match.create',
        'match.invite.users',
        'match.confirm.participation',
        'match.enter.result',
        'match.manage.any',
        'rating.view',
        'friends.view',
        'friends.add',
        'booking.request',
        'booking.manage',
        'booking.cancel',
        'shop.view',
        'order.create',
        'order.process',
        'order.view.own',
        'order.view.any',
        'wallet.view',
        'wallet.topup',
        'wallet.reserve',
        'wallet.writeoff',
        'wallet.force.adjust',
        'subscription.view',
        'subscription.purchase',
        'subscription.cancel',
        'chat.view',
        'chat.send',
        'chat.files.send',
        'survey.fill',
        'survey.view.own',
        'survey.view.any',
        'specialists.view',
        'specialists.manage',
        'sport_objects.view',
        'sport_objects.manage',
        'services.manage',
        'news.view',
        'news.manage',
        'analytics.view',
        'finance.view',
        'finance.export',
        'assistants.manage',
        'system.notifications.receive',
        'admin.logs.view'
    )
);

DELETE FROM permissions
WHERE name IN (
    'auth.register',
    'auth.login',
    'profile.view.own',
    'profile.edit.own',
    'profile.view.any',
    'profile.block',
    'profile.unblock',
    'change.user.subscription',
    'sport_plan.view',
    'sport_plan.generate.ai',
    'sport_plan.edit',
    'progress.view',
    'schedule.view',
    'activity.create',
    'match.create',
    'match.invite.users',
    'match.confirm.participation',
    'match.enter.result',
    'match.manage.any',
    'rating.view',
    'friends.view',
    'friends.add',
    'booking.request',
    'booking.manage',
    'booking.cancel',
    'shop.view',
    'order.create',
    'order.process',
    'order.view.own',
    'order.view.any',
    'wallet.view',
    'wallet.topup',
    'wallet.reserve',
    'wallet.writeoff',
    'wallet.force.adjust',
    'subscription.view',
    'subscription.purchase',
    'subscription.cancel',
    'chat.view',
    'chat.send',
    'chat.files.send',
    'survey.fill',
    'survey.view.own',
    'survey.view.any',
    'specialists.view',
    'specialists.manage',
    'sport_objects.view',
    'sport_objects.manage',
    'services.manage',
    'news.view',
    'news.manage',
    'analytics.view',
    'finance.view',
    'finance.export',
    'assistants.manage',
    'system.notifications.receive',
    'admin.logs.view'
);

DELETE FROM roles
WHERE name IN ('guest', 'client', 'assistant', 'admin');
